import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { resolveGreeting, clampGreeting, GREETING_MAX } from "./agentConfig.js";

/* The opening greeting is now owner-editable, and the promise attached to that
 * input is "the AI says exactly this, every time". Two things have to hold, and
 * both are easy to break by accident:
 *
 *  1. The greeting is spoken as Vapi's `firstMessage` with
 *     `firstMessageMode: "assistant-speaks-first"`. That mode plays the string
 *     through TTS directly — the LLM never generates the first turn, so it
 *     cannot paraphrase it. Switching to "assistant-waits-for-user", or feeding
 *     firstMessage anything other than the greeting, silently breaks the
 *     promise while every test still passes.
 *  2. Nothing rewrites an owner's wording on the way through.
 */

const vapiSrc = readFileSync(resolve(import.meta.dirname, "../services/vapi.ts"), "utf8");
const summarizerSrc = readFileSync(
  resolve(import.meta.dirname, "../services/promptSummarizer.ts"),
  "utf8",
);

const CUSTOM = "Namaste! Ram Ram, thank you for calling. How may I assist?";

describe("the owner's greeting reaches the caller verbatim", () => {
  it("is spoken as firstMessage, not generated by the model", () => {
    expect(vapiSrc).toMatch(/firstMessage: greeting,/);
  });

  it("uses assistant-speaks-first, which plays the string through TTS as written", () => {
    // "assistant-waits-for-user" would hand the first turn to the LLM, which
    // would then compose its own greeting from the prompt.
    expect(vapiSrc).toMatch(/firstMessage: greeting,\s*\n\s*firstMessageMode: "assistant-speaks-first"/);
  });

  it("takes the greeting straight from the owner's config", () => {
    expect(vapiSrc).toMatch(
      /const greeting = resolveGreeting\(config\.identity\.greetingMessage, businessName\)/,
    );
  });

  it("keeps a custom greeting exactly as written, punctuation and all", () => {
    expect(resolveGreeting(CUSTOM, "Some Other Business")).toBe(CUSTOM);
  });

  it("does not rewrite a custom greeting when the business is renamed", () => {
    // The rename path only re-derives greetings WE generated.
    expect(resolveGreeting(CUSTOM, "Renamed Ltd")).toBe(CUSTOM);
    expect(resolveGreeting(CUSTOM, "")).toBe(CUSTOM);
  });

  it("survives the prompt compressor — the summariser must keep it word for word", () => {
    // The live prompt is LLM-compressed before it reaches Vapi. The greeting is
    // on the summariser's verbatim list; losing that line would let the model
    // reword the greeting quoted in the prompt.
    expect(summarizerSrc).toMatch(/Keep VERBATIM, word-for-word: the opening greeting in quotes/);
  });

  it("only truncates past the cap the editor itself enforces", () => {
    const long = "A".repeat(GREETING_MAX + 50);
    expect(clampGreeting(long)).toHaveLength(GREETING_MAX);
    // Anything a customer can actually type in the UI passes through untouched.
    expect(clampGreeting(CUSTOM)).toBe(CUSTOM);
  });
});
